# name: 部署到render

# on:
#   push:
#     branches:
#       - main

# jobs:
  # deploy_pokemon:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: 检出代码
  #     uses: actions/checkout@v2
  #   - uses: actions/setup-node@v4
  #     with:
  #         node-version: '20'  

  #   - name: 部署到Render
  #     uses: johnbeynon/render-deploy-action@v0.0.8
  #     with:
  #       service-id: 'srv-cpi3upsf7o1s73bbn5hg'  # Replace with your Render Service ID
  #       api-key: {{ secrets.RENDER_API_KEY }}

name: 进行版本号提升并创建Git标签

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  bump_version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch  # 默认提升补丁级别版本
          WITH_V: true  # 标签前加v
          DRY_RUN: false  # 实际执行版本提升和标签创建
          PRERELEASE: false  # 默认不创建预发布版本标签
