name: 部署到render

on:
  push:
    branches:
      - main

jobs:
  deploy_pokemon:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with:
          node-version: '20'  

    - name: 部署到Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: 'srv-cpi3upsf7o1s73bbn5hg'  # Replace with your Render Service ID
        api-key: ${{ secrets.RENDER_API_KEY }}